config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :posts do
    member do
      get "like", to: "posts#upvote"
      get "dislike", to: "posts#downvote"
    end
    resources :comments
  end

  root 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
	acts_as_votable
	belongs_to :user
	has_many :comments

	has_attached_file :image, styles: { medium: "700x500#", small: "350x250>" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
	has_many :comments
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.for(:sign_up) << :name
  	devise_parameter_sanitizer.for(:account_update) << :name
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
	def create
		@post = Post.find(params[:post_id])
		@comment = Comment.create(params[:comment].permit(:content))
		@comment.user_id = current_user.id
		@comment.post_id = @post.id

		if @comment.save
			redirect_to post_path(@post)
		else
			render 'new'
		end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
	before_action :authenticate_user!, except: [:index, :show]
	def index
		@posts = Post.all.order("created_at DESC")
	end

	def show
		@comments = Comment.where(post_id: @post)
		@random_post = Post.where.not(id: @post).order("RANDOM()").first
	end

	def new
		@post = current_user.posts.build
	end

	def create
		@post = current_user.posts.build(post_params)

		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @post.update(post_params)
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post.destroy
		redirect_to root_path
	end

	def upvote
		@post.upvote_by current_user
		redirect_to :back
	end

	def downvote
		@post.downvote_by current_user
		redirect_to :back
	end
	private

	def find_post
		@post = Post.find(params[:id])
	end

	def post_params
		params.require(:post).permit(:title, :link, :description, :image)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/comments/_form.html.haml
= simple_form_for([@post, @post.comments.build]) do |f|
	= f.input :content, label: "Reply to thread"
	= f.button :submit, class: "button"

app/views/layouts/application.html.haml
!!!
%html
%head
	%title Dribble
	= stylesheet_link_tag    'application', media: 'all'
	= javascript_include_tag 'application'
	%link{:rel => "stylesheet", :href => "http://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.1/normalize.min.css"}
	%link{:rel => "stylesheet", :href => "http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css"}
	= csrf_meta_tags
%body
	%header
		.wrapper.clearfix
			#logo= link_to "Dribble", root_path
			%nav
				- if user_signed_in?
					= link_to current_user.name, edit_user_registration_path
					= link_to "Add New Inspiration", new_post_path, class: "button"
				- else
					= link_to "Sign in", new_user_session_path
					= link_to "Sign Up", new_user_registration_path, class: "button"
	%p.notice= notice
	%p.alert= alert
	.wrapper
		= yield

app/views/posts/_form.html.haml
= simple_form_for @post do |f|
	= f.input :image
	= f.input :title
	= f.input :link
	= f.input :description

	= f.button :submit

app/views/posts/edit.html.haml
%h1 Edit Inspiration

= render 'form'

app/views/posts/index.html.haml
- if user_signed_in?
	%p#intro
		Hello
		= current_user.name
		%br/
		%span
			Share your inspiration and see what's inspiring others.
- else
	%p#intro
		What's your inspiration?
		%br/
		%span
			Share your inspiration and see what's inspiring others.

#posts
	- @posts.each do |post|
		.post
			.post_image
				= link_to (image_tag post.image.url(:small)), post
			.post_content
				.title
					%h2= link_to post.title, post
				.data.clearfix
					%p.username
						Shared by
						= post.user.name
					%p.buttons
						%span
							%i.fa.fa-comments-o
							= post.comments.count
						%span
							%i.fa.fa-thumbs-o-up
							= post.get_likes.size
	

app/views/posts/new.html.haml
%h1 Add New Inspiration

= render 'form'

app/views/posts/show.html.haml
#post_show
	%h1= @post.title
	%p.username
		Shared by
		= @post.user.name
		about
		= time_ago_in_words(@post.created_at)
	.clearfix
		.post_image_description
			= image_tag @post.image.url(:medium)
			.description= simple_format(@post.description)
		.post_data
			= link_to "Visit Link", @post.link, class: "button"
			= link_to like_post_path(@post), method: :get, class: "data" do
				%i.fa.fa-thumbs-o-up
				= pluralize(@post.get_upvotes.size, "Like")
			= link_to dislike_post_path(@post), method: :get, class: "data" do
				%i.fa.fa-thumbs-o-down
				= pluralize(@post.get_downvotes.size, "Dislike")
			%p.data
				%i.fa.fa-comments-o
				= pluralize(@post.comments.count, "Comment")
			- if @post.user == current_user
				= link_to "Edit", edit_post_path(@post), class: "data"
				= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure?" }, class: "data"
		#random_post
			%h3 Random Inspiration
			.post
				.post_image
					= link_to (image_tag @random_post.image.url(:medium)), post_path(@random_post)
				.post_content
					.title
						%h2= link_to @random_post.title, post_path(@random_post)
					.data.clearfix
						%p.username
							Shared by
							= @random_post.user.name
						%p.buttons
							%span
								%i.fa.fa-comments-o
								= @random_post.comments.count
							%span
								%i.fa.fa-thumbs-o-up
								= @random_post.get_likes.size

#comments
	%h2.comment_count= pluralize(@post.comments.count, "Comment")
	- @comments.each do |comment|
		.comment
			%p.username= comment.user.name
			%p.content= comment.content

	= render "comments/form"